apiVersion: v1
kind: Service
metadata:
  name: ms-cadastro-funcionario
  namespace: github-copilot
  labels:
    app: ms-cadastro-funcionario
spec:
  type: ClusterIP
  selector:
    app: ms-cadastro-funcionario
  ports:
    - name: http
      port: 8007
      targetPort: 8007
